### ISSUE TITLE
visualization tsne

### ISSUE THREAD

**Issue by mhmism** [crj32/Spectrum#1]
Thanks a lot for this amazing R package. 

What the tsne and umap functions have been removed from the cran package?

Kind regards
Mahmoud

**Comment by crj32** [comment]
Hi

I removed those functions because I didn't want the dependencies.

You can get them again from the github repository, crj32.

Basically it is just tsne or umap run on a distance matrix, so not the same
as normal tsne or umap. Easy.

Best regards

Chris

**Comment by mhmism** [comment]
Thank you for your fast reaction! That's helpful.

Merry Christmas! enjoy your time.
